image: maven:3.5.3-jdk-8
  
stages:
  - sonar
  - deploiement
  
tests:
  stage: tests
  script: 
  - mvn test
  only:
  - branches
  
sonarqube:
  stage: sonar
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: http://localhost:8080
    SONAR_ANALYSIS_MODE: issues
  script:
  - gitlab-sonar-scanner
  
sonarqube-reports:
  stage: sonar
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: http://localhost:8080
    SONAR_ANALYSIS_MODE: publish
  script:
  - gitlab-sonar-scanner
  
deploiement_dev:
  stage: deploiement
  script: 
    - echo 'Deploy sur le serv de developpement'
  only:
    - /^dev.*$/
  except:
    - branches

deploiement_master:
  stage: deploiement
  script: 
    - echo 'Deploy sur le serv de production'
  only:
    - master
  except:
    - branches

