image: maven:3.5.3-jdk-8
  
stages:
  - sonar
  - deploiement

sonarqube:
  stage: sonar
  image: hiorgserver/gitlab-sonar-scanner
  variables:
    SONAR_URL: "http://localhost:8888"
    SONAR_PROJECT_KEY: "com.projet.ecommerce"
    SONAR_PROJECT_NAME: "e-commerce"
    SONAR_PROJECT_VERSION: "1.0"
    SONAR_GITLAB_COMMENT: "true"
    SONAR_PUBLISH: "true"
  script:
  - /usr/bin/sonar-scanner-run.sh
  
deploiement_dev:
  stage: deploiement
  script: 
    - echo 'Deploy sur le serv de developpement'
  only:
    - /^dev.*$/
  except:
    - branches

deploiement_master:
  stage: deploiement
  script: 
    - echo 'Deploy sur le serv de production'
  only:
    - master
  except:
    - branches

