image: maven:3.5.3-jdk-8
  
stages:
  - tests
  - deploiement
  
tests:
  stage: tests
  script: 
  - echo 'test'
  only:
  - branches
  
deploiement_dev:
  stage: deploiement
  script: 
    - mvn package
  artifacts:
    paths:
    - target/*.jar
    expire_in: 1h
  only:
    - dev
  except:
    - branches


deploiement_master:
  stage: deploiement
  script: 
    - mvn package
  artifacts:
    paths:
    - target/*.jar
    expire_in: 1h
  only:
    - master
  except:
    - branches

