image: maven:3.5.3-jdk-8
  
stages:
  - tests
  - deploiement
  
tests:
  stage: tests
  script: 
  - mvn test

deploiement_dev:
  stage: deploiement
  script: 
    - echo 'Deploiement sur le serveur de developpement'
  only:
    - dev

deploiement_master:
  stage: deploiement
  script: 
    - echo 'Deploiement sur le serveur de production'
  only:
    - master

