image: maven:3.5.3-jdk-8
  
stages:
  - tests
  - deploiement
  
tests:
  stage: tests
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: http://10.6.67.150:9000
    SONAR_ANALYSIS_MODE: issues
  script:
  - echo 'test'
  only:
  - branches
  
deploiement_dev:
  stage: deploiement
  script: 
    - maven build
  artifacts:
    paths:
    - jar
    expire_in: 1 week
  only:
    - dev

deploiement_master:
  stage: deploiement
  script: 
    - maven build
  artifacts:
    paths:
    - jar
    expire_in: 1 week
  only:
    - master
